[supervisord]
nodaemon=true
logfile=/opt/argus/share/supervisor/supervisord.log
pidfile=/opt/argus/share/supervisor/supervisord.pid
childlogdir=/opt/argus/share/supervisor

[unix_http_server]
file=/opt/argus/share/supervisor/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///opt/argus/share/supervisor/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf
