[program:tailscaled]
command=/opt/argus/bin/tailscaled --tun=userspace-networking --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055
autostart=true
autorestart=true
priority=10
stdout_logfile=/opt/argus/share/supervisor/tailscaled.log
stderr_logfile=/opt/argus/share/supervisor/tailscaled.log
